### PR TITLE
Add support for authentication against knox

### PR DESCRIPTION
**Pull request by jannopaas**
Merged changes from https://github.com/mfranklin1/pylivy to current state of the repostiory. The aim is to add authentication against knox. Testing succeeded.

### CODE REVIEW

**Comment by jannopaas** [comment]
@acroz can you review please and merge if all ok

**Comment by jannopaas** [comment]
Any updates?

**Comment by acroz** [comment]
Hi @jannopaas - sorry for the delay on this.

Unfortunately this PR does not pass the automated tests due to formatting not confirming with flake8 and incorrect type hints. Due to this and not having unit tests, I've implemented auth based on this PR in a slightly more general way with unit tests in PR #37.

I'm not super happy with always setting proxyUser as foobar when authentication is being used, but I'll expose proxyUser as an available keyword argument, which should hopefully allow you to use the workaround for Knox.

**Comment by acroz** [comment]
PR #40 implements proxyUser support - please let me know if this allows you to use knox auth as desired.

**Comment by jannopaas** [comment]
Thank you @acroz, this satisfies my needs!

**Pull request closed without merging**
