### PR TITLE
Shell conf extend

### PR DESCRIPTION
**Pull request by parisni**
This maj add all livy args for shell.
I did'nt add any tests so far.
This is about #34

### CODE REVIEW

**Comment by crleblanc** [comment]
I'm interested in the 'pyFiles' option from this PR.  I could possibly use the 'files' and 'archives' options too  The Livy docs are very sparse so I would need to do some experimentation first.  It's unlikely that I'll use the other options, at least at this stage.

I had a quick look at the test failures.  It appears that livy/session.py:147 is too long and some of the type annotations in livy/client.py should be `list[str]` instead of `list()`.  These are very simple changes to make.  I'm happy to make a new PR with these changes and additional unit tests if @parisni is not available.

I can also manually test the code on an EMR cluster running Livy 0.5.0-incubating to make sure it works correctly.

**Comment by parisni** [comment]
Hi,

Indeed, I am not available these days. Would be great to improve my code (which i am using in production so far)

**Comment by crleblanc** [comment]
Hi Parisni,

It's probably easiest for me to make a new pull request based on your changes with some minor tweaks. Thanks for you work.  The py_files keyword arg is working nicely for me with a Spark EMR and Livy.  If the new PR is merged we should close this one.

**Comment by acroz** [comment]
This is now merged through #53 - thanks for the contibution!

**Pull request closed without merging**
