### PR TITLE
Added PYSPARK3 to valid sessions

### PR DESCRIPTION
**Pull request by jnalley**
I was getting `RuntimeError: read not supported for sessions of kind SessionKind.PYSPARK3`

This seems to fix it.

### CODE REVIEW

**Comment by acroz** [comment]
Thanks for the contribution! There are some mypy errors occurring in the tests, but I suspect this is due to some change in the latest mypy as it's unrelated to adding this entry. I'll have a look at fixing these issues on master so you can rebase.

**Comment by jnalley** [comment]
Sounds good - thanks!

**Comment by acroz** [comment]
I've fixed the typing errors - can you rebase this off master please?

**Comment by jnalley** [comment]
Thanks!  - rebased now.

**Comment by acroz** [comment]
I've released this to PyPI in version 0.3.0. Thanks again for the contribution!

**Pull request merged**
